name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t udm-rasterise-coverage .       

      - name: test
        run: docker run -v $PWD/data:/data --env EXTENT=459000,202000,501000,244000 --env LAYER=test_layer --name udm-rasterise-coverage udm-rasterise-coverage 
              