name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t udm-rasterise-coverage .       

      - name: test
        run: docker run -v $PWD/data:/data --env EXTENT=459000,202000,501000,244000 --env LAYER=test_layer --name udm-rasterise-coverage udm-rasterise-coverage 
        
      - name: test2
        run: docker run -v $PWD/data:/data --env EXTENT=459000,202000,501000,244000 --env INPUTFILE=test_region.shp --env LAYER=test_layer --name udm-rasterise-coverage-test2 udm-rasterise-coverage 
       
      - name: test3
        run: docker run -v $PWD/data:/data --env EXTENT=459000,202000,501000,244000 --env INPUTFILE=test_region.shp --env LAYER=test_layer --env OUTPUTTITLE=test_output --env OUTPUTDESCRIPTION='A test output file' --name udm-rasterise-coverage-test3 udm-rasterise-coverage 
