name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t coverage-calculator .

      - name: test
        run: docker run -v $PWD/data:/data --name coverage-calculator coverage-calculator

      - name: test extent
        run: docker run -v $PWD/data:/data --env EXTENT=419284,570156,420836,571597 --name coverage-calculator-extent coverage-calculator