name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t coverage-calculator .

      - name: test
        run: docker run --name coverage-calculator coverage-calculator
